# This file gives the mapping between DatasetType and the
# `lsst.daf.butler.Formatter` that handles it.
write_recipes: !include writeRecipes.yaml
default:
  lsst.obs.base.formatters.fitsExposure.FitsExposureFormatter:
    # default is the default recipe regardless but this demonstrates
    # how to specify a default write parameter
    recipe: default
TablePersistable: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
Wcs: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
Psf: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
CoaddInputs: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
VisitInfo: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
ApCorr: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
PhotoCalib: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
TransmissionCurve: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
Camera: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
Detector: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
Catalog: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
PeakCatalog: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
SimpleCatalog: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
SourceCatalog: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
ObjectMaskCatalog: lsst.pipe.tasks.objectMasks.RegionFileFormatter
DataFrame: lsst.daf.butler.formatters.parquet.ParquetFormatter
Defects: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
QECurve: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
CrosstalkCalib: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
ImageF: lsst.obs.base.formatters.fitsExposure.FitsExposureFormatter
ImageU: lsst.obs.base.formatters.fitsExposure.FitsExposureFormatter
DecoratedImageU: lsst.obs.base.formatters.fitsExposure.FitsExposureFormatter
MaskX: lsst.obs.base.formatters.fitsExposure.FitsExposureFormatter
MaskedImageF: lsst.obs.base.formatters.fitsExposure.FitsExposureFormatter
Exposure: lsst.obs.base.formatters.fitsExposure.FitsExposureFormatter
ExposureF: lsst.obs.base.formatters.fitsExposure.FitsExposureFormatter
ExposureI: lsst.obs.base.formatters.fitsExposure.FitsExposureFormatter
SkyMap: lsst.daf.butler.formatters.pickle.PickleFormatter
Background: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter
Config: lsst.daf.butler.formatters.pexConfig.PexConfigFormatter
Packages:
  formatter: lsst.obs.base.formatters.packages.PackagesFormatter
  parameters:
    format: yaml
PropertyList: lsst.daf.butler.formatters.yaml.YamlFormatter
PropertySet: lsst.daf.butler.formatters.yaml.YamlFormatter
NumpyArray: lsst.daf.butler.formatters.pickle.PickleFormatter
Plot: lsst.daf.butler.formatters.matplotlib.MatplotlibFormatter
MetricValue: lsst.daf.butler.formatters.yaml.YamlFormatter
BrighterFatterKernel: lsst.daf.butler.formatters.pickle.PickleFormatter
StructuredDataDict: lsst.daf.butler.formatters.yaml.YamlFormatter
Filter: lsst.obs.base.formatters.filter.FilterFormatter
BrightStarStamps: lsst.obs.base.formatters.fitsGeneric.FitsGenericFormatter