storageClasses:
  StructuredDataDict:
    pytype: dict
  StructuredDataList:
    pytype: list
  TablePersistable:
    pytype: lsst.afw.table.io.Persistable
  Wcs:
    pytype: lsst.afw.geom.skyWcs.SkyWcs
  Psf:
    pytype: lsst.afw.detection.Psf
  CoaddInputs:
    pytype: lsst.afw.image.CoaddInputs
  VisitInfo:
    pytype: lsst.afw.image.VisitInfo
  ApCorr:
    pytype: lsst.afw.image.ApCorrMap
  PhotoCalib:
    pytype: lsst.afw.image.PhotoCalib
  TransmissionCurve:
    pytype: lsst.afw.image.TransmissionCurve
  Camera:
    pytype: lsst.afw.cameraGeom.Camera
  Detector:
    pytype: lsst.afw.cameraGeom.Detector
  Image: &Image
    pytype: lsst.afw.image.Image
    assembler: lsst.daf.butler.assemblers.exposureAssembler.ExposureAssembler
    parameters:
      - bbox
      - origin
  ImageF:
    inheritsFrom: Image
    pytype: lsst.afw.image.ImageF
  ImageI:
    inheritsFrom: Image
    pytype: lsst.afw.image.ImageI
  ImageU:
    inheritsFrom: Image
    pytype: lsst.afw.image.ImageU
  DecoratedImage:
    pytype: lsst.afw.image.DecoratedImage
  DecoratedImageU:
    inheritsFrom: DecoratedImage
    pytype: lsst.afw.image.DecoratedImageU
  Mask:
    pytype: lsst.afw.image.Mask
    assembler: lsst.daf.butler.assemblers.exposureAssembler.ExposureAssembler
    parameters:
      - bbox
      - origin
  MaskX:
    inheritsFrom: Mask
    pytype: lsst.afw.image.MaskX
  MaskedImage:
    pytype: lsst.afw.image.MaskedImage
  MaskedImageF:
    inheritsFrom: MaskedImage
    pytype: lsst.afw.image.MaskedImageF
  MaskedImageU:
    inheritsFrom: MaskedImage
    pytype: lsst.afw.image.MaskedImageU
  MaskedImageI:
    inheritsFrom: MaskedImage
    pytype: lsst.afw.image.MaskedImageI
  Catalog:
    pytype: lsst.afw.table.BaseCatalog
  PeakCatalog:
    pytype: lsst.afw.detection.PeakCatalog
  SimpleCatalog:
    pytype: lsst.afw.table.SimpleCatalog
  SourceCatalog:
    pytype: lsst.afw.table.SourceCatalog
  ObjectMaskCatalog:
    pytype: lsst.pipe.tasks.objectMasks.ObjectMaskCatalog
  DataFrame:
    pytype: pandas.DataFrame
    components:
      columns: DataFrameIndex
    parameters:
      - columns
  DataFrameIndex:
    pytype: pandas.Index
  SkyMap:
    pytype: lsst.skymap.BaseSkyMap
  PropertySet:
    pytype: lsst.daf.base.PropertySet
  PropertyList:
    pytype: lsst.daf.base.PropertyList
  Defects:
    pytype: lsst.meas.algorithms.Defects
  QECurve:
    pytype: lsst.meas.algorithms.Curve
  CrosstalkCalib:
    pytype: lsst.ip.isr.CrosstalkCalib
  Filter:
    pytype: lsst.afw.image.Filter
  Exposure:
    pytype: lsst.afw.image.Exposure
    assembler: lsst.obs.base.exposureAssembler.ExposureAssembler
    parameters:
      - bbox
      - origin
    components:
      image: Image
      mask: Mask
      variance: Image
      wcs: Wcs
      psf: Psf
      photoCalib: PhotoCalib
      visitInfo: VisitInfo
      apCorrMap: ApCorr
      coaddInputs: CoaddInputs
      transmissionCurve: TransmissionCurve
      metadata: PropertyList
      filter: Filter
  ExposureF:
    inheritsFrom: Exposure
    pytype: lsst.afw.image.ExposureF
    components:
      image: ImageF
      mask: MaskX
      variance: ImageF
  ExposureI:
    inheritsFrom: Exposure
    pytype: lsst.afw.image.ExposureI
    components:
      image: ImageI
      mask: MaskX
      variance: ImageF
  ExposureU:
    inheritsFrom: Exposure
    pytype: lsst.afw.image.ExposureU
    components:
      image: ImageU
      mask: MaskX
      variance: ImageF
  Background:
    pytype: lsst.afw.math.BackgroundList
  Config:
    pytype: lsst.pex.config.Config
  Packages:
    pytype: lsst.base.Packages
  NumpyArray:
    pytype: numpy.ndarray
  StrayLightData:
    pytype: lsst.ip.isr.StrayLightData
  BrighterFatterKernel:
    pytype: lsst.cp.pipe.makeBrighterFatterKernel.BrighterFatterKernel
  Thumbnail:
    pytype: numpy.ndarray
  Plot:
    pytype: matplotlib.figure.Figure
  MetricValue:
    pytype: lsst.verify.Measurement
  BrightStarStamps:
    pytype: lsst.meas.algorithms.brightStarStamps.BrightStarStamps